### ISSUE TITLE
Replace with icons

### ISSUE THREAD

**Issue by syde0** [shuhart/StepView#1]
Hi sir,

First off all, this is a cool library,
now for a quick question, is it possible to replace each progress numbers with icon?

Thanks :)

**Comment by shuhart** [comment]
Sure, it's possible but I can't do it right now. Maybe in nearest future. You are welcome to do pull request for this.

**Comment by hardikamal** [comment]
@shuhart Any updates on this?

**Comment by shuhart** [comment]
I am looking forward to support this in the next major version.

**Comment by sajidjutt7** [comment]
@shuhart this icons addition in replacement of number. Have this functionality added to this library yet or not?

**Comment by shuhart** [comment]
I don't think so. Unfortunately I don't have enough time to continue working on this library. You can just copy/paste it to your project and add necessary changes, since the source code is pretty simple
