### ISSUE TITLE
is it possible to change selectedStepNumbers text i.e 1,2,3,4..... inside of circle as per choice text or drawable.

### ISSUE THREAD

**Issue by RahilRK** [shuhart/StepView#16]

**Comment by shuhart** [comment]
#1

**Comment by RahilRK** [comment]
in next version isn't it.....bro...

**Comment by shuhart** [comment]
I would do it when I find spare time.

**Comment by RahilRK** [comment]
drawable is truly need, bro make sure you remain me when you update and add it in future.....

**Comment by shuhart** [comment]
Would be implemented in #1
