### ISSUE TITLE
not working and visible inside ScrollView....

### ISSUE THREAD

**Issue by RahilRK** [shuhart/StepView#17]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    tools:context="com.e_commerce_app.rahil.e_commerce.Step">

    <android.support.v7.widget.Toolbar
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="?attr/colorPrimaryDark"
        android:theme="@style/ToolbarStyle">

    </android.support.v7.widget.Toolbar>

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <LinearLayout
            android:layout_width="match_parent"
            android:padding="20dp"
            android:layout_height="wrap_content"
            android:orientation="vertical">
            
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <com.shuhart.stepview.StepView
            android:id="@+id/step_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:padding="16dp"
            app:sv_selectedCircleColor="@color/colorAccent"
            app:sv_selectedTextColor="@color/colorAccent"
            app:sv_stepLineWidth="1dp"
            app:sv_stepPadding="4dp"
            app:sv_nextTextColor="@color/colorAccent"
            app:sv_nextStepLineColor="@color/colorAccent"
            app:sv_doneCircleColor="@color/colorAccent"
            app:sv_doneStepLineColor="@color/colorAccent"
            app:sv_doneCircleRadius="12dp"
            app:sv_selectedCircleRadius="12dp"
            app:sv_selectedStepNumberColor="@color/colorPrimary"
            app:sv_stepViewStyle="@style/StepView"
            app:sv_doneStepMarkColor="@color/colorPrimary"
            app:sv_stepNumberTextSize="12sp"
            app:sv_animationType="All"
            app:sv_steps="@array/steps"
            app:sv_stepsNumber="4"/>
    </LinearLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingLeft="2.5dp"
        android:paddingRight="2.5dp"
        android:layout_marginTop="10dp"
        android:orientation="vertical"
        android:background="@color/white"
        >

        <android.support.v7.widget.RecyclerView
            android:id="@+id/order_item_detail_recycler_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

    </LinearLayout>
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal">

        <Button
            android:id="@+id/trackorderbtid"
            android:layout_width="0dp"
            android:layout_weight="1"
            android:layout_height="wrap_content"
            android:background="@drawable/border2"
            android:text="Track"
            android:layout_marginTop="10dp"
            android:layout_marginRight="5dp"
            android:textColor="@color/lightmaroon" />

        <Button
            android:id="@+id/cancelorderbtid"
            android:layout_width="0dp"
            android:layout_weight="1"
            android:layout_height="wrap_content"
            android:background="@drawable/border2"
            android:text="Cancel"
            android:layout_marginTop="10dp"
            android:layout_marginLeft="5dp"
            android:textColor="@color/lightmaroon" />

    </LinearLayout>
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@drawable/border"
        android:layout_marginTop="10dp"
        android:padding="5dp"
        android:orientation="vertical">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:textSize="15dp"
            android:textColor="@color/black"
            android:text="ORDER SUMMARY"/>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:layout_marginTop="10dp">

            <TextView
                android:layout_width="0dp"
                android:layout_weight="1"
                android:layout_height="wrap_content"
                android:text="Sub Total"/>

            <LinearLayout
                android:layout_width="0dp"
                android:layout_weight="0.5"
                android:gravity="center"
                android:layout_height="wrap_content">

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="Rs 800"
                    android:textColor="@color/black_50"/>

            </LinearLayout>

        </LinearLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:gravity="end"

            android:layout_marginTop="10dp">

            <TextView
                android:layout_width="0dp"
                android:layout_weight="1"
                android:layout_height="wrap_content"
                android:text="Shipping"/>

            <LinearLayout
                android:layout_width="0dp"
                android:layout_weight="0.5"
                android:gravity="center"
                android:layout_height="wrap_content">

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="Rs 200"
                    android:textColor="@color/black_50"/>

            </LinearLayout>

        </LinearLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:layout_marginTop="10dp">

            <TextView
                android:layout_width="0dp"
                android:layout_weight="1"
                android:layout_height="wrap_content"
                android:text="Total Payable"
                android:textStyle="bold"/>

            <LinearLayout
                android:layout_width="0dp"
                android:layout_weight="0.5"
                android:gravity="center"
                android:layout_height="wrap_content">

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="Rs 1000"
                    android:textStyle="bold"
                    android:textColor="@color/black_50"/>

            </LinearLayout>

        </LinearLayout>

    </LinearLayout>
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@drawable/border"
        android:layout_marginTop="10dp"
        android:padding="5dp"
        android:orientation="vertical">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:textSize="15dp"
            android:textColor="@color/black"
            android:text="Payment Mode"/>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:padding="5dp"
            android:layout_marginTop="10dp">

            <TextView
                android:layout_width="0dp"
                android:layout_weight="1"
                android:layout_height="wrap_content"
                android:text="COD"
                android:textStyle="bold"/>

        </LinearLayout>

    </LinearLayout>
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@drawable/border"
        android:layout_marginTop="10dp"
        android:padding="5dp"
        android:orientation="vertical">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:textSize="15dp"
            android:textColor="@color/black"
            android:text="Shipping Address"/>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:padding="5dp"
            android:layout_marginTop="10dp">

            <TextView
                android:layout_width="0dp"
                android:layout_weight="1"
                android:layout_height="wrap_content"
                android:text="A-19, Silver Complex, Daman."
                android:textStyle="bold"/>

        </LinearLayout>

    </LinearLayout>
        </LinearLayout>
    </ScrollView>
</LinearLayout>

**Comment by shuhart** [comment]
Try not to mix things up. 
`app:sv_steps="@array/steps"
 app:sv_stepsNumber="4`
Choose only one of the options. Either sv_steps or sv_stepsNumber.

**Comment by eduochieng** [comment]
I'm having the same issue. It is not showing inside NestedScrollView.

**Comment by shuhart** [comment]
Fixed in 1.3.2
