### ISSUE TITLE
Content is not allowed

### ISSUE THREAD

**Issue by rademoh** [shuhart/StepView#19]
when i add gradle file i get this 
StepViewExample/app/src/main/res/font/iran_sans_mobile.ttf
Error:Execution failed for task ':app:mergeDebugResources'.
> StepViewExample/app/src/main/res/font/iran_sans_mobile.ttf:1:1: Error: Content is not allowed in prolog.

**Comment by shuhart** [comment]
What do you mean by "adding gradle file"?

**Comment by rademoh** [comment]
when i add stepView gradle dependency and the project is rebuilding i get the error

**Comment by shuhart** [comment]
Make sure you use the last version of the library.

**Comment by rademoh** [comment]
am using 
'com.shuhart.stepview:stepview:1.2.6'

**Comment by shuhart** [comment]
Then try rebuild. My guess is that you updated the library and some old
resources become redundant.

**Comment by shuhart** [comment]
Looks like it's your local problem.

**Comment by rademoh** [comment]
worked nw upgraded my IDE to 3.0
