### ISSUE TITLE
Can't add more than three items

### ISSUE THREAD

**Issue by EpsilonOrionis** [shuhart/StepView#2]
Hi, I need to add more than three circles in my app. I tried to add four circles to your example and it behaves in the same way. Adding more than three circles make the view to overlap the last items. Try it and you will with your own eyes.

Thank you in advance, this library is very useful, but you need to fix this issue to make it perfect.

**Comment by shuhart** [comment]
Hi! I fixed this in the version 1.0.1. Let me know if the issue is gone.

**Comment by EpsilonOrionis** [comment]
Solved
