### ISSUE TITLE
Last Circle cut in half if only using Number of Steps (no text from string array)

### ISSUE THREAD

**Issue by idevdroidapps** [shuhart/StepView#21]
If only using circles by setting number of steps (not using string array of text labels), the last circle is not drawn completely.  The last circle is only half drawn.

**Comment by limallucas96** [comment]
I guess I have the same problem like you. Followed all instructions and the last element is shown out of the screen. Im using constraint layout btw.

**Comment by limallucas96** [comment]
![image](https://user-images.githubusercontent.com/36681970/39648655-4e46f834-4fb9-11e8-9f85-0ceda1ad59b5.png)

**Comment by shuhart** [comment]
How do you specify the width of the widget?

**Comment by shuhart** [comment]
Yep, found a bug with the right padding for the only circles mode. Fixed in 1.2.7. 
Btw, this padding bug is not as bad as it looks on yours screenshot, so provide additional information on how you specified the width and height. Looks like there is not enough space for the widget to be properly drawn in your case.

**Comment by limallucas96** [comment]
![image](https://user-images.githubusercontent.com/36681970/39668060-0adbf11c-509a-11e8-8084-5c9c8dc613fe.png)

**Comment by shuhart** [comment]
I've tested your config. Everything works fine in 1.2.7. So, check it out.

**Comment by limallucas96** [comment]
I can't compile the version 1.2.7. Failed to resolve: com.shuhart.stepview:stepview:1.2.7

**Comment by limallucas96** [comment]
Thank you sir, it's working smooth.

**Comment by shuhart** [comment]
Need some to sync with jcenter, I guess.
