### ISSUE TITLE
Unselected cirlce color

### ISSUE THREAD

**Issue by billy9222** [shuhart/StepView#22]
Is there any method of setting unselected step color ?

**Comment by shuhart** [comment]
You can use:
```
app:sv_doneCircleColor="@color/colorAccent"
app:sv_doneStepLineColor="@color/colorAccent"
```

**Comment by billy9222** [comment]
@shuhart i am talking about unselected circle color!

**Comment by shuhart** [comment]
It's not yet supported, but fairly easy to implement. I would be added in the next version.

**Comment by billy9222** [comment]
Great (Y)

**Comment by donpaul120** [comment]
Please, Has this feature been implemented?

**Comment by shuhart** [comment]
Well, I tried but it doesn't look good. When you are going forward or backward a next circle revealing animation is triggered. If we decide to give a next circle some color it completely messes up the animation.

**Comment by testica** [comment]
@shuhart this features was discarded? I have the same need of @billy9222. It is possible that you open a branch with your progress about ?

**Comment by shuhart** [comment]
For now, I have no idea how to implement it without breaking the animation, sorry.
