### ISSUE TITLE
view invisible if parent is set to wrap_content

### ISSUE THREAD

**Issue by bny-mobile** [shuhart/StepView#26]
I'm trying to use it the view in a recyclerview, wich means I'm setting the parent to wrap_content, when I do this the StepView is no longer visible.

**Comment by shuhart** [comment]
Post your code to reproduce.

**Comment by bny-mobile** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <TextView
        android:id="@+id/tv_name"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fontFamily="@font/avgb"
        android:text="NAME"
        android:textAppearance="@android:style/TextAppearance.DeviceDefault.Large"
        android:textColor="@color/white" />
    <TextView
        android:id="@+id/tv_info"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fontFamily="@font/avgb"
        android:text="info"
        android:textAppearance="@android:style/TextAppearance.DeviceDefault.Small"
        android:textColor="@color/white" />
    <com.shuhart.stepview.StepView
        android:id="@+id/step_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="2dp"
        app:sv_selectedCircleColor="@color/orange"
        app:sv_selectedTextColor="@color/orange"
        app:sv_stepLineWidth="1dp"
        app:sv_stepPadding="4dp"
        app:sv_nextTextColor="@color/white_50p"
        app:sv_nextStepLineColor="@color/white_50p"
        app:sv_doneCircleColor="@color/white"
        app:sv_doneStepLineColor="@color/white"
        app:sv_doneCircleRadius="3dp"
        app:sv_selectedCircleRadius="4dp"
        app:sv_selectedStepNumberColor="@color/vub_blue"
        app:sv_stepViewStyle="@style/StepView"
        app:sv_stepsNumber="4"
        app:sv_doneStepMarkColor="@color/white"
        app:sv_stepNumberTextSize="0sp"
        app:sv_animationType="None"
        app:sv_typeface="@font/avant_garde"/>
</LinearLayout>`

I also tried with a constraintlayout and both show the view if parent is set to match_parent, but not when set to wrap_content

**Comment by anex06** [comment]
I have used this in simple activity and its working but whenever i use in Listview its throwing an error..
Please help me i'm getting the following error..
java.lang.NullPointerException: Attempt to read from null array
                      at com.shuhart.stepview.StepView.drawText(StepView.java:643)
                      at com.shuhart.stepview.StepView.drawStep(StepView.java:573)
                      at com.shuhart.stepview.StepView.onDraw(StepView.java:528)
                      at android.view.View.draw(View.java:17451)
                      at android.view.View.updateDisplayListIfDirty(View.java:16390)
                      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3841)
                      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3821)
                      at android.view.View.updateDisplayListIfDirty(View.java:16344)

**Comment by shuhart** [comment]
A bunch of measuring problems were fixed in 1.3.2. I added samples with RecyclerView and ScrollView so check those out.
