### ISSUE TITLE
Replacing Numbers with Images

### ISSUE THREAD

**Issue by ArlonTM** [shuhart/StepView#27]
Hi.

It would be so cool to provide the ability to show images instead of numbers. 
An extra attribute of type of array could be added to the view; just like the one for steps, but an array of drawables this time.

Also, instead of having each step filled with a check sign once the user has moved to the next step, you could just change the background color while keeping the step number/index (or image, in the case of the new feature I'm proposing).

Apologies if it's too much asking. I know that drawing images on a canvas requires a bit more (work) than merely drawing a character.

Thanks,

**Comment by shuhart** [comment]
Oh, #1 mentioned the same as yours one, actually. I'm going to close this one.
