### ISSUE TITLE
Showing step hints on Top and Bottom of circle

### ISSUE THREAD

**Issue by majidkabir** [shuhart/StepView#31]
When all step hints shows on bottom of step circles, sometimes hints overlap each other, for solving this problem you can add an option to StepView that show every other hint on top of the circle.
This can prevent overlapping the hints.

**Comment by shuhart** [comment]
Use the last version. The overlapping issue is fixed.

**Comment by shuhart** [comment]
Can't see how placing texts above or below the circles would save space. It would rather be inconsistent with common UX pattern. For example, look on BottomNavigationView from support library. 
I will look into issue with RTL texts, because it looks horrible in your example.

**Comment by shuhart** [comment]
Going to close this one. RTL issue is to be fixed in #25
