### ISSUE TITLE
Next step

### ISSUE THREAD

**Issue by EpsilonOrionis** [shuhart/StepView#4]
Vertical StepView.

<com.shuhart.stepview.StepView
	android:id="@+id/step_view"
	android:layout_width="match_parent"
	android:layout_height="wrap_content"
	android:padding="16dp"
	**app:orientation="horizontal|vertical"**
	.../>

What do you think about this?

**Comment by shuhart** [comment]
That would require quite a rewriting. And personally I don't find it very useful since having a vertically aligned widget like ViewPager is not a common UI pattern. But anyway, this could be done along with the support of RTL but not in the nearest future.
