### ISSUE TITLE
how to change next step circle color

### ISSUE THREAD

**Issue by NasarIqbal** [shuhart/StepView#45]
I working on a design in which I need a different color for select and done circles ... I can set value for done circle but ... unfortunately could not find attribute to set the color for next circle. how do I do that ... here is my current setting 

<com.shuhart.stepview.StepView
            android:id="@+id/step_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:padding="16dp"
            android:layout_marginTop="130dp"
            android:background="@android:color/transparent"
            app:sv_selectedCircleColor="@color/colorPrimary"
            app:sv_selectedTextColor="@android:color/white"
            app:sv_stepLineWidth="5dp"
            android:layout_gravity="center_vertical"
            app:sv_stepPadding="0dp"
            app:sv_nextTextColor="@android:color/black"
            app:sv_nextStepLineColor="@color/colorLightRed"
            app:sv_doneCircleColor="@color/colorPrimary"
            app:sv_doneStepLineColor="@color/colorPrimary"
            app:sv_doneTextColor="@color/colorPrimary"
            app:sv_doneCircleRadius="12dp"
            app:sv_selectedCircleRadius="12dp"
            app:sv_selectedStepNumberColor="@color/colorAccent"
            app:sv_stepViewStyle="@style/StepView"
            app:sv_doneStepMarkColor="@android:color/white"
            app:sv_stepNumberTextSize="12sp"
            app:sv_animationType="All"
            app:sv_typeface="@font/sfuitextmedium"/>

**Comment by shuhart** [comment]
What you want is not supported by this library. I know that there is a Material Design component for mentioned requirements here https://material.io/archive/guidelines/components/steppers.html#steppers-types-of-steps but in order to implement this I have to sit and rewrite couple of things. For now, I don't have enough spare time for this.

**Comment by shuhart** [comment]
Support for this is added in 1.5.0. Check the Readme (bottom of it) to find out how to use it.
