### ISSUE TITLE
Gradle 5.6.4 migration issue

### ISSUE THREAD

**Issue by rwendelboe** [shuhart/StepView#57]
I keep getting these 3 errors  after upgrading to gradle 5.6.4

AAPT: error: style attribute 'attr/sv_animationDuration (aka com.comcast.optek.xm.clouddev:attr/sv_animationDuration)' not found.

AAPT: error: resource attr/sv_background (aka com.comcast.optek.xm.clouddev:attr/sv_background) not found.

AAPT: error: resource attr/sv_animationDuration (aka com.comcast.optek.xm.clouddev:attr/sv_animationDuration) not found.

**Comment by Javed1191** [comment]
I am geting following error after upgrading 3.6.0 gradle

1) APT: error: style attribute 'attr/sv_animationDuration (aka com.utc:attr/sv_animationDuration)' not found.
2) AAPT: error: style attribute 'attr/sv_textSize (aka com.utc:attr/sv_textSize)' not found.
3) AAPT: error: resource attr/sv_textSize (aka com.utc:attr/sv_textSize) not found.
4) AAPT: error: resource attr/sv_background (aka com.utc:attr/sv_background) not found.
5) AAPT: error: resource attr/sv_animationDuration (aka com.utc:attr/sv_animationDuration) not found.

**Comment by shuhart** [comment]
All were updated dependencies in 1.5.1. Update to this version.

**Comment by joelpremkumar** [comment]
did u find a solution to this problem i am facing the same problem 

AAPT: error: style attribute 'attr/sv_animationDuration (aka com.example.design2:attr/sv_animationDuration)' not found.

**Comment by joelpremkumar** [comment]
> I am geting following error after upgrading 3.6.0 gradle
> 
> 1. APT: error: style attribute 'attr/sv_animationDuration (aka com.utc:attr/sv_animationDuration)' not found.
> 2. AAPT: error: style attribute 'attr/sv_textSize (aka com.utc:attr/sv_textSize)' not found.
> 3. AAPT: error: resource attr/sv_textSize (aka com.utc:attr/sv_textSize) not found.
> 4. AAPT: error: resource attr/sv_background (aka com.utc:attr/sv_background) not found.
> 5. AAPT: error: resource attr/sv_animationDuration (aka com.utc:attr/sv_animationDuration) not found.

Did u find a soultion ??

**Comment by rwendelboe** [comment]
Unfortunately I did not.
