### ISSUE TITLE
Need a nextStepNumberColor property

### ISSUE THREAD

**Issue by FingerArt** [shuhart/StepView#60]

**Comment by MujahidHi5** [comment]
please use `sv_nextTextColor`

**Comment by MujahidHi5** [comment]
You can use : `      app:sv_nextStepCircleColor="@color/grey_10"
            app:sv_nextStepCircleEnabled="true"
            app:sv_nextStepLineColor="@color/colorAccent"`

**Comment by MujahidHi5** [comment]
You can use : 
app:sv_nextStepCircleColor="@color/grey_10" 
app:sv_nextStepCircleEnabled="true" 
app:sv_nextStepLineColor="@color/colorAccent" 
app:sv_nextTextColor="@color/colorAccent"

**Comment by shuhart** [comment]
nextTextColor, doneTextColor are used to determine both a color for a step number text and a title for the step. Changing color for step number text independently is supported only for selected step. You are welcome to do a PR for that, as I don't feel that this feature is necessary and have no plans to implement it myself.
