### ISSUE TITLE
Setting Typeface

### ISSUE THREAD

**Issue by SirLordPouya** [shuhart/StepView#9]
hi
is there a way to set typeface for the StepView ?

**Comment by shuhart** [comment]
Check out version 1.2.2 
You can specify a custom typeface in xml:
`app:typeface="@font/roboto_italic`
or in java:
`stepView.getState().typeface(ResourcesCompat.getFont(context, R.font.roboto_italic).commit();`

**Comment by SirLordPouya** [comment]
thanks.
but could you please change this line : 
        <attr name="typeface" format="reference" />
to someThing unique Like : 
        <attr name="stp_typeface" format="reference" />
to prevent conflict with other libraries?

**Comment by shuhart** [comment]
Have you missed something?

**Comment by SirLordPouya** [comment]
:D 
yea lots of things I think.
im prety sure I pasted them.


but could you please change this line :
`<attr name="typeface" format="reference" `/>
to someThing unique Like :
` <attr name="stp_typeface" format="reference" `/>
to prevent conflict with other libraries?

**Comment by shuhart** [comment]
Yep, I forgot about that. I will just reuse "android:typeface".

**Comment by shuhart** [comment]
Fixed in 1.2.3

**Comment by SirLordPouya** [comment]
it works perfectly.
i only saw this after setting typeface : (see the numbers in the circle)
<img width="320" alt="screen shot 2018-02-04 at 11 07 25 pm" src="https://user-images.githubusercontent.com/13719096/35781513-525ab482-0a00-11e8-8865-3f862639f74e.png">
<img width="318" alt="screen shot 2018-02-04 at 11 06 53 pm" src="https://user-images.githubusercontent.com/13719096/35781514-547004ca-0a00-11e8-92ab-337f28bec8c8.png">

**Comment by shuhart** [comment]
Strange. Could you provide a font file you use? I will look into this issue tomorrow.

**Comment by SirLordPouya** [comment]
[IRANSansMobile.ttf.zip](https://github.com/shuhart/StepView/files/1693238/IRANSansMobile.ttf.zip)
Thanks for your help :)

**Comment by shuhart** [comment]
Fixed in 1.2.4
